import os
from PyQt5.QtWidgets import QMessageBox

def set_default_options(self):
        # Set default options based on the selected default
        default_option = self.default_dropdown.currentText()
        if default_option == "Eigenrays":
            self.fields["Bellhop Executable"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bellhop_exe/bellhopcxx"))
            self.fields["SSP File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ssp.mat"))
            self.fields["Bathymetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/bty.mat"))
            self.fields["Altimetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ati.mat"))
            self.fields["Filename"].setText("run_eigenrays_3500")
            self.fields["Data File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/runs/"))
            self.fields["Save File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/run_saves/"))
            self.fields["Source Longitude"].setText("-122.83")
            self.fields["Source Latitude"].setText("47.77")
            self.fields["Receiver Longitude"].setText("-122.85")
            self.fields["Receiver Latitude"].setText("47.71")
            self.fields["Frequency"].setText("3500.0")
            self.fields["SSPOPT(1)"].setCurrentText("S: Cubic Spline Interpolation")
            self.fields["SSPOPT(2)"].setCurrentText("A: Acoustic half-space (Surface information required)")
            self.fields["SSPOPT(3)"].setCurrentText("F: attenuation corresponds to (dB/m)kHz")
            self.fields["SSPOPT(4)"].setCurrentText("' ': Default parameter")   
            self.fields["SSPOPT(5)"].setCurrentText("*: Use if including an *.ati file for surface shape")
            self.fields["Surface Height"].setText("0.0")
            self.fields["Surface Compressional Speed"].setText("343.0")
            self.fields["Surface Shear Speed"].setText("0.0")
            self.fields["Surface Density"].setText("1.2")
            self.fields["Surface Attenuation"].setText("0.0")
            self.fields["Bottom Type"].setCurrentText("A: acoustic half-space below water column (need BOTTOM-LINE)")
            self.fields["Include Bathymetry"].setCurrentText("*: include if wanting to use a *.bty file")
            self.fields["Roughness"].setText("0.0")
            self.fields["Bottom Height"].setText("0.0")
            self.fields["Bottom Compressional Speed"].setText("1600.0")
            self.fields["Bottom Shear Speed"].setText("0.0")
            self.fields["Bottom Density"].setText("1.8")
            self.fields["Bottom Attenuation"].setText("0.0")
            self.fields["Number of Source Depths"].setText("1")
            self.fields["Source Depths"].setText("20.0")
            self.fields["Number of Receiver Depths"].setText("1")
            self.fields["Receiver Depths"].setText("20.0")
            self.fields["Number of Receiver Ranges"].setText("1")
            self.fields["Receiver Ranges"].setText("7.0")
            self.fields["Ray Compute Type"].setCurrentText("E: Write Eigenray coordinates")
            self.fields["Number of Beams"].setText("10001")
            self.fields["Launch Angles"].setText("-25.0, 25.0")
            self.fields["Step Size"].setText("10.0")

        elif default_option == "Ray Coordinates":
            self.fields["Bellhop Executable"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bellhop_exe/bellhopcxx"))
            self.fields["SSP File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ssp.mat"))
            self.fields["Bathymetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/bty.mat"))
            self.fields["Altimetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ati.mat"))
            self.fields["Filename"].setText("run_ray_coor_3500")
            self.fields["Data File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/runs/"))
            self.fields["Save File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/run_saves/"))
            self.fields["Source Longitude"].setText("-122.83")
            self.fields["Source Latitude"].setText("47.77")
            self.fields["Receiver Longitude"].setText("-122.85")
            self.fields["Receiver Latitude"].setText("47.71")
            self.fields["Frequency"].setText("3500.0")
            self.fields["SSPOPT(1)"].setCurrentText("S: Cubic Spline Interpolation")
            self.fields["SSPOPT(2)"].setCurrentText("A: Acoustic half-space (Surface information required)")
            self.fields["SSPOPT(3)"].setCurrentText("F: attenuation corresponds to (dB/m)kHz")
            self.fields["SSPOPT(4)"].setCurrentText("' ': Default parameter")   
            self.fields["SSPOPT(5)"].setCurrentText("*: Use if including an *.ati file for surface shape")
            self.fields["Surface Height"].setText("0.0")
            self.fields["Surface Compressional Speed"].setText("343.0")
            self.fields["Surface Shear Speed"].setText("0.0")
            self.fields["Surface Density"].setText("1.2")
            self.fields["Surface Attenuation"].setText("0.0")
            self.fields["Bottom Type"].setCurrentText("A: acoustic half-space below water column (need BOTTOM-LINE)")
            self.fields["Include Bathymetry"].setCurrentText("*: include if wanting to use a *.bty file")
            self.fields["Roughness"].setText("0.0")
            self.fields["Bottom Height"].setText("0.0")
            self.fields["Bottom Compressional Speed"].setText("1600.0")
            self.fields["Bottom Shear Speed"].setText("0.0")
            self.fields["Bottom Density"].setText("1.8")
            self.fields["Bottom Attenuation"].setText("0.0")
            self.fields["Number of Source Depths"].setText("1")
            self.fields["Source Depths"].setText("20.0")
            self.fields["Number of Receiver Depths"].setText("1")
            self.fields["Receiver Depths"].setText("20.0")
            self.fields["Number of Receiver Ranges"].setText("1")
            self.fields["Receiver Ranges"].setText("7.0")
            self.fields["Ray Compute Type"].setCurrentText("R: Write ray coordinates")
            self.fields["Number of Beams"].setText("10001")
            self.fields["Launch Angles"].setText("-25.0, 25.0")
            self.fields["Step Size"].setText("10.0")
            
        elif default_option == "Transmission Loss":
            self.fields["Bellhop Executable"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bellhop_exe/bellhopcxx"))
            self.fields["SSP File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ssp.mat"))
            self.fields["Bathymetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/bty.mat"))
            self.fields["Altimetry File"].setText(os.path.join(os.getcwd(), "Justin_Work/App/bty_ssp_ati/ati.mat"))
            self.fields["Filename"].setText("run_tl_3500")
            self.fields["Data File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/runs/"))
            self.fields["Save File Directory"].setText(os.path.join(os.getcwd(), "Justin_Work/App/run_saves/"))
            self.fields["Source Longitude"].setText("-122.83")
            self.fields["Source Latitude"].setText("47.77")
            self.fields["Receiver Longitude"].setText("-122.85")
            self.fields["Receiver Latitude"].setText("47.71") 
            self.fields["Frequency"].setText("3500.0")
            self.fields["SSPOPT(1)"].setCurrentText("S: Cubic Spline Interpolation")
            self.fields["SSPOPT(2)"].setCurrentText("V: Vacuum above surface (SURFACE-LINE not required)")
            self.fields["SSPOPT(3)"].setCurrentText("F: attenuation corresponds to (dB/m)kHz")
            self.fields["SSPOPT(4)"].setCurrentText("' ': Default parameter")   
            self.fields["SSPOPT(5)"].setCurrentText("*: Use if including an *.ati file for surface shape")
            self.fields["Surface Height"].setText("0.0")
            self.fields["Surface Compressional Speed"].setText("343.0")
            self.fields["Surface Shear Speed"].setText("0.0")
            self.fields["Surface Density"].setText("1.2")
            self.fields["Surface Attenuation"].setText("0.0")
            self.fields["Bottom Type"].setCurrentText("A: acoustic half-space below water column (need BOTTOM-LINE)")
            self.fields["Include Bathymetry"].setCurrentText("*: include if wanting to use a *.bty file")
            self.fields["Roughness"].setText("0.0")
            self.fields["Bottom Height"].setText("0.0")
            self.fields["Bottom Compressional Speed"].setText("1600.0")
            self.fields["Bottom Shear Speed"].setText("0.0")
            self.fields["Bottom Density"].setText("1.8")
            self.fields["Bottom Attenuation"].setText("0.0")
            self.fields["Number of Source Depths"].setText("1")
            self.fields["Source Depths"].setText("20.0")
            self.fields["Number of Receiver Depths"].setText("201")
            self.fields["Receiver Depths"].setText("0.0, 200.0")
            self.fields["Number of Receiver Ranges"].setText("501")
            self.fields["Receiver Ranges"].setText("0.0, 7.0")
            self.fields["Ray Compute Type"].setCurrentText("C: Write coherent acoustic pressure")
            self.fields["Number of Beams"].setText("0")
            self.fields["Launch Angles"].setText("-89.0, 89.0")
            self.fields["Step Size"].setText("0.0")